#pragma once

void do_high(void);
void do_low(void);
void do_af(void);
void do_if(void);
void do_pitch(void);
void do_wpm(void);
void do_comp(void);
void do_mic(void);
void do_power(void);

void do_agc(void);
void do_mode(void);
void do_10m(void);
void do_12m(void);
void do_split(void);
void do_15m(void);
void do_17m(void);
void do_20m(void);
void do_record(void);
void do_rx(void);
void do_tx(void);
void do_30m(void);
void do_40m(void);
void do_80m(void);
void do_rit(void);
void do_span(void);
void do_vfo(void);
void do_step(void);